# Файл docker-compose.yml

# Версия docker-compose
version: '3'

# Перечень volume
volumes:
  pg_data_production:
  static_volume:

# Перечень контейнеров
services:
  # Имя и описание первого контейнера; имя выбирает разработчик. 
  # Это контейнер БД
  db:
    # Из какого образа запустить контейнер:
    image: postgres:13.10
    # Файл (или список файлов) с переменными окружения
    env_file: .env
    # Какой volume подключить для этого контейнера
    volumes:
      - pg_data_production:/var/lib/postgresql/data
  # Имя и описание контейнера с бэкендом
  backend:
    # Из какого Dockerfile собирать образ для этого контейнера:
    image: nikpetrishchev/taski_backend
    env_file: .env
    volumes:
      - static_volume:/backend_static
  # Имя третьего контейнера. Это контейнер с фронтендом
  frontend:
    image: nikpetrishchev/taski_frontend
    env_file: .env
    command: cp -r /app/build/. /frontend_static/
    volumes:
      - static_volume:/frontend_static
  gateway:
    image: nikpetrishchev/taski_gateway
    env_file: .env
    volumes:
      - static_volume:/staticfiles/
    ports:
      - 8000:80
